theme: jekyll-theme-modernist
title: Welcome!
description: My name is Caroline Carrozzini and I am a senior biology student at Southern New Hampshire University. Here you will find some of my recent work.
